"""Regression tests for check_file_sizes.py. Run: python3 -m unittest discover -s scripts"""
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

CHECKER = Path(__file__).with_name("check_file_sizes.py")


class FileSizeCheckerTest(unittest.TestCase):
    def setUp(self):
        self.repo = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.repo)
        subprocess.run(["git", "init", "-q", str(self.repo)], check=True)
        shutil.copy(CHECKER, self.repo / "check.py")

    def write(self, name, text):
        path = self.repo / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        subprocess.run(["git", "-C", str(self.repo), "add", name], check=True)

    def source(self, name, lines):
        self.write(name, "x\n" * lines)

    def manifest(self, name, *entries):
        self.write(name, "# comment\n" + "".join("\t".join(map(str, e)) + "\n" for e in entries))

    def check(self, *args):
        result = subprocess.run(
            [sys.executable, "check.py", *args], cwd=self.repo, capture_output=True, text=True
        )
        return result.returncode, result.stdout + result.stderr

    def assertPasses(self, *args):
        code, output = self.check(*args)
        self.assertEqual(code, 0, output)
        return output

    def assertFails(self, expected, *args):
        code, output = self.check(*args)
        self.assertEqual(code, 1, output)
        self.assertIn(expected, output)

    def test_baseline_file_passes_at_its_ceiling(self):
        self.source("a.go", 1200)
        self.manifest("file-size-baseline.tsv", ("a.go", 1200))
        self.assertIn("baseline 1200/1200 'a.go'", self.assertPasses())

    def test_new_file_over_cap_fails(self):
        self.source("a.go", 1001)
        self.assertFails("FAIL 1001 'a.go'")

    def test_baseline_growth_fails(self):
        self.source("a.go", 1201)
        self.manifest("file-size-baseline.tsv", ("a.go", 1200))
        self.assertFails("exceeds baseline ceiling 1200")

    def test_shrinkage_passes_without_raising_ceiling(self):
        self.source("a.go", 1100)
        self.manifest("file-size-baseline.tsv", ("a.go", 1200))
        self.assertIn("baseline 1100/1200", self.assertPasses())

    def test_retired_file_entry_is_stale(self):
        self.source("a.go", 1000)
        self.manifest("file-size-baseline.tsv", ("a.go", 1200))
        self.assertFails("stale baseline entry")

    def test_deleted_or_untracked_entry_is_stale(self):
        self.manifest("file-size-baseline.tsv", ("gone.go", 1200))
        self.assertFails("stale baseline entry")

    def test_malformed_baseline_entries_fail(self):
        for entry, expected in [
            (("a.go",), "malformed"),
            (("a.go", "abc"), "limit must be"),
            (("a.go", 900), "limit must be"),
            (("../a.go", 1200), "not repository-relative"),
            (("a.go", 1200, "extra"), "malformed"),
        ]:
            with self.subTest(entry=entry):
                self.source("a.go", 1200)
                self.manifest("file-size-baseline.tsv", entry)
                self.assertFails(expected)

    def test_duplicate_baseline_entry_fails(self):
        self.source("a.go", 1200)
        self.manifest("file-size-baseline.tsv", ("a.go", 1200), ("a.go", 1200))
        self.assertFails("duplicate")

    def test_symlink_entry_and_manifest_fail(self):
        self.source("a.go", 1200)
        os.symlink("a.go", self.repo / "b.go")
        subprocess.run(["git", "-C", str(self.repo), "add", "b.go"], check=True)
        self.manifest("file-size-baseline.tsv", ("b.go", 1200))
        self.assertFails("is a symlink")
        self.manifest("real.tsv", ("a.go", 1200))
        (self.repo / "file-size-baseline.tsv").unlink()
        os.symlink("real.tsv", self.repo / "file-size-baseline.tsv")
        self.assertFails("must not be a symlink")

    def test_untracked_manifest_fails(self):
        self.source("a.go", 1200)
        (self.repo / "file-size-baseline.tsv").write_text("a.go\t1200\n", encoding="utf-8")
        self.assertFails("must be tracked")

    def test_generated_file_is_exempt_and_baseline_entry_for_it_is_stale(self):
        self.write("gen.go", "// Code generated by x. DO NOT EDIT.\n" + "x\n" * 1200)
        self.assertPasses()
        self.manifest("file-size-baseline.tsv", ("gen.go", 1201))
        self.assertFails("stale baseline entry")

    def test_unbounded_exception_on_new_over_cap_file_is_rejected(self):
        self.source("a.go", 1500)
        self.manifest("file-size-exceptions.tsv", ("a.go", "approved reason"))
        self.assertFails("malformed file-size-exceptions.tsv entry")

    def test_bounded_exception_on_non_baseline_file(self):
        self.source("a.go", 1500)
        self.manifest("file-size-exceptions.tsv", ("a.go", 1500, "approved reason"))
        self.assertIn("exception 1500 'a.go'", self.assertPasses())
        self.source("a.go", 1501)
        self.assertFails("exceeds exception limit 1500")

    def test_unbounded_exception_on_baseline_file_is_rejected(self):
        # The #537 shape: a two-column exception for a file already in the baseline.
        self.source("runtime/doctor.go", 1620)
        self.manifest("file-size-baseline.tsv", ("runtime/doctor.go", 1611))
        self.manifest("file-size-exceptions.tsv", ("runtime/doctor.go", "approved for #537"))
        self.assertFails("malformed file-size-exceptions.tsv entry")

    def test_bounded_exception_allows_growth_up_to_its_limit_only(self):
        self.source("a.go", 1210)
        self.manifest("file-size-baseline.tsv", ("a.go", 1200))
        self.manifest("file-size-exceptions.tsv", ("a.go", 1210, "approved reason"))
        self.assertIn("exception 1210 'a.go'", self.assertPasses())
        self.source("a.go", 1211)
        self.assertFails("exceeds exception limit 1210")

    def test_bounded_exception_not_above_ceiling_is_rejected(self):
        self.source("a.go", 1200)
        self.manifest("file-size-baseline.tsv", ("a.go", 1200))
        self.manifest("file-size-exceptions.tsv", ("a.go", 1200, "reason"))
        self.assertFails("must state a limit above its ceiling")


    def pin(self, lines):
        """Commit a.go at the given size and point the copied checker's pin at that commit."""
        self.source("a.go", lines)
        subprocess.run(["git", "-C", str(self.repo), "-c", "user.name=t", "-c", "user.email=t@t",
                        "commit", "-qm", "pin"], check=True)
        sha = subprocess.check_output(["git", "-C", str(self.repo), "rev-parse", "HEAD"], text=True).strip()
        script = self.repo / "check.py"
        text = script.read_text(encoding="utf-8")
        self.assertIn(PIN, text)
        script.write_text(text.replace(PIN, sha), encoding="utf-8")

    def test_verified_baseline_at_or_below_pinned_count_passes(self):
        self.pin(1611)
        for ceiling in (1611, 1500):
            with self.subTest(ceiling=ceiling):
                self.source("a.go", 1400)
                self.manifest("file-size-baseline.tsv", ("a.go", ceiling))
                self.assertIn("baseline verified", self.assertPasses(VERIFY))

    def test_raised_baseline_ceiling_fails_verification(self):
        self.pin(1611)
        self.manifest("file-size-baseline.tsv", ("a.go", 9999))
        self.assertPasses()
        self.assertFails("exceeds 1611 at the pin", VERIFY)

    def test_new_baseline_path_fails_verification(self):
        self.pin(1611)
        self.source("b.go", 1200)
        self.manifest("file-size-baseline.tsv", ("b.go", 1200))
        self.assertFails("was not over 1000 lines at the pin", VERIFY)

    def test_unavailable_pin_fails_closed(self):
        self.source("a.go", 1200)
        self.manifest("file-size-baseline.tsv", ("a.go", 1200))
        self.assertFails("is unavailable", VERIFY)

    def test_unknown_argument_is_rejected(self):
        self.assertFails("usage", "--verify")


PIN = "001efd613a40b4b367c6617085e40a24286fac47"
VERIFY = "--verify-baseline"

if __name__ == "__main__":
    unittest.main()
